//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clavis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClavisModelContainer : DbContext
    {
        public ClavisModelContainer()
            : base("name=ClavisModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lock> Locks { get; set; }
        public virtual DbSet<LockGroup> LockGroups { get; set; }
        public virtual DbSet<LockOwner> LockOwners { get; set; }
        public virtual DbSet<LockUser> LockUsers { get; set; }
    }
}
